### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by haidong-wu** [notplus/MTCNN-PureC#2]
请问ARM cotex M3适用吗？

**Comment by haidong-wu** [comment]
M3没有FPU单元，能运行你的算法吗

**Comment by notplus** [comment]
建议参考[ARM-CMSIS_5](https://github.com/ARM-software/CMSIS_5)，我这里使用了其中的DSP库，看官方描述是适用于全部Cortex-M

**Comment by haidong-wu** [comment]
你好，方便加个微信吗（17356535419），代码我用codeblocks跑出来了，但是最后没有返回我两个坐标点（x1,y1）,（x2,y2）,以及Ppoint，耽误您一点时间，详细请教一下，万分感谢。

**Comment by notplus** [comment]
已加，微信头像同Github账户头像
