### ISSUE TITLE
想询问您 input1.txt 是怎么产生的?

### ISSUE THREAD

**Issue by b51ak47** [notplus/MTCNN-PureC#3]
想询问您 input1.txt 是怎么产生的?

THX

**Comment by notplus** [comment]
应该是RGB CHW格式的图片，你可以测试一下，时间比较久远了

**Comment by b51ak47** [comment]
您好
因为输入的档案一直有误，只有您的input1.txt和input2.txt可以正常执行，想跟您确认，
我打开看input1.txt 一共有920656个数?
                input2.txt 一共有920896个数?
您的CWH 格式是指，一张彩色影像(640,480) 排列成:
R R R R R ... ... R G G G G G ... G B B B....B
(R一共307,200) (G一共307,200)(B一共307,200)
这样的方式排列吗?
因为蛮关键的，麻烦您了~
谢谢

**Comment by notplus** [comment]
你可以使用如下python代码得到 RGB CHW格式的数据，将其保存为txt读取即可，需要注意匹配图像尺寸大小。
```python
img = cv2.imread("001.jpg")
img_ = img[:,:,::-1].transpose((2,0,1))
```
另外示例的input1.txt有问题，缺少了部分数据，关于输入数据我稍后在README中更新说明。

**Comment by b51ak47** [comment]
您好 我尝试引用这个方法，写成input3.txt，但好像还是不行输入，会 Segmentation fault (core dumped)
但是您的input 就没有问题~太神奇了~
如果大神知道怎么解决，还请您帮忙~
感谢~

import cv2
import numpy
import sys

numpy.set_printoptions(threshold=sys.maxsize)

**img = cv2.imread("lena.jpg")
img_ = img[:,:,::-1].transpose((2,0,1))**

with open('input3.txt', 'w') as f2:
    for item in img_:
    	for item2 in item:
    		for item3 in item2:
        		f2.write("%s " % item3)

**Comment by notplus** [comment]
更新的README里有更详细的脚本，另外可以通过gdb调试一下，看下具体报错位置。

**Comment by b51ak47** [comment]
Hi ~ 大神我解决了，要用自己的image file 
cmake 我没有注意到要config 到自己的image
add_custom_command(TARGET ${PROJECT_NAME}
                   POST_BUILD
                   COMMAND ${CMAKE_COMMAND} -E copy_if_different
                   "${PROJECT_SOURCE_DIR}/input1.txt" "${PROJECT_SOURCE_DIR}/input2.txt" **"${PROJECT_SOURCE_DIR}/input3.txt"**


成功可以inference自己的image
剩下的就是我自己在找training 
Onet.txt Pnet.txt Rnst.txt 的问题了~
非常感谢~
感谢大神帮忙~  很有用的代码~
